sudo apt-get update
sudo apt-get install -y build-essential
sudo apt install curl
curl -sL [ttps://deb.nodesource.com/setup_10.x](https://deb.nodesource.com/setup_10.x) | sudo -E bash -
sudo -apt-get install -y nodejs
sudo apt install npm
npm install
npm run build
