apiVersion: v1
kind: Service
metadata:
  name: moine-frontend-svc
  labels:
    app: moine-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      name: moine-frontend
      protocol: TCP
      targetPort: 3000
  selector:
    app: moine-frontend
